repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: .venv/Scripts/black.exe
        language: script
        types: [python]

      - id: isort
        name: isort
        entry: .venv/Scripts/isort.exe
        language: script
        types: [python]

      - id: flake8
        name: flake8
        entry: .venv/Scripts/flake8.exe
        language: script
        types: [python]

      - id: bandit
        name: bandit
        entry: .venv/Scripts/bandit.exe
        language: script
        args: ["-r", "."]

      - id: detect-secrets
        name: detect-secrets
        entry: .venv/Scripts/detect-secrets.exe
        language: script
        args: ["scan"]
